### PR TITLE
feat: Bypass confirmation dialog `railway down`

### LINKED ISSUE #272: Allow `railway down` to bypass confirm check
This comes from a discussion in the [discord](https://discord.com/channels/713503345364697088/943650028696768532/1018945444358922310) channel.

### PR DESCRIPTION
**Pull request by Guergeiro**
Closes #272

### CODE REVIEW

**Comment by JakeCooper** [comment]
Awesome! Can you fix the lint check here?

**Comment by Guergeiro** [comment]
> Awesome! Can you fix the lint check here?

Should be fixed now!

**Review by wyzlle — APPROVED** [review]
LGTM!

**Comment by Zack-Bloodshot** [comment]
Thankss!!

**Review by JakeCooper — APPROVED** [review]

**Pull request merged**
