### PR TITLE
fix npm install for windows

### LINKED ISSUE #201: NPM install is broken for windows
`npm i -g @railway/cli` is broken as it is trying to read the `package.json` version which does not match any of the released versions.

I have made a potential fix here https://github.com/maxs-rose/cli/commit/bd50117f8fa93b80ecb434a00da2b1f8652a3e01 the issue is it will only grab the latest release and that's why I haven't made a pull request for it. 

If we are happy with the idea I can make a pull request for it.

### PR DESCRIPTION
**Pull request by maxs-rose**
closes #201

### CODE REVIEW

**Review by JakeCooper — APPROVED** [review]
Pure delete fix nice!

**Comment by JakeCooper** [comment]
BTW if you're in the Discord @maxs-rose plz comment there and we can assign you the contributor role!

**Comment by maxs-rose** [comment]
What can I say deleting code is fun hehe

**Comment by JuanM04** [comment]
@maxs-rose can you confirm it's working on Windows?

**Comment by maxs-rose** [comment]
@JuanM04 
image

**Comment by maxs-rose** [comment]
image

**Comment by maxs-rose** [comment]
gave me a scare there thought it had broken since I tested it last night 😅

**Comment by JuanM04** [comment]
lol, sorry. I was wondering if it would throw an error when calling `bin/railway` instead of `bin/railway.exe`, but it seems that windows handle it automatically

**Comment by maxs-rose** [comment]
Either npm or windows handles that, not sure which, since a lot of cli tools work like that as well if you look under `%userprofile%/AppData/Roaming/npm`.

**Pull request merged**
