### PR TITLE
Added arm in build for

### PR DESCRIPTION
**Pull request by GrimZZZ-404**
Added arm in build for environment. It defaults to 386, amd64 and arm64. Thus, it wasn't able to work in arm devices.

### CODE REVIEW

**Review by tle-alt — APPROVED** [review]

**Comment by tle-alt** [comment]
Does this work on termux? I got some refused connection error. When I compiled it. Had to make some change in the settings to make it work

**Comment by JakeCooper** [comment]
Is there a way to incorporate the CGO_ENABLED change into this PR such that the above would work for Android/Termux?

**Comment by GrimZZZ-404** [comment]
Adding Android might need other dependencies(gcc for android). I will create a new PR If the build is successful. I will close this. Is that okay?

**Comment by JakeCooper** [comment]
Yup sounds good!

**Comment by GrimZZZ-404** [comment]
Sorry, It auto merged in this

**Comment by ian** [comment]
Any ideas on when this can be merged? Builds are still failing on latest @railway/cli

```
npm ERR! path /Users/ian/.nvm/versions/node/v16.13.0/lib/node_modules/@railway/cli
npm ERR! command failed
npm ERR! command sh -c go-npm install
npm ERR! Installation is not supported for this architecture: arm64
npm ERR! Invalid inputs
```

**Review by JakeCooper — APPROVED** [review]

**Comment by JakeCooper** [comment]
This SHOULD be handled via @JuanM04's install script I believe

Tested on my M1 and seems to work. Can someone else verify?

**Comment by JuanM04** [comment]
> This SHOULD be handled via @JuanM04's install script I believe

These lines have to be modified: https://github.com/railwayapp/cli/blob/64f6a1715d226ffd48af887687f6796134325624/npm-install/config.js#L36-L37

Also, is Android still necessary? Isn't `CGO_ENABLED=1` enough?

**Comment by JakeCooper** [comment]
CC @GrimZZZ-404

**Comment by GrimZZZ-404** [comment]
Recent linux release works perfectly fine on termux. I dont think android is necessary now.

**Comment by GrimZZZ-404** [comment]
Some people are still facing issues on Android. I guess we should keep Android

**Pull request closed without merging**
